### ISSUE TITLE
Issue loading HWS custom devices at runtime

### ISSUE THREAD

**Issue by rphillipsnwt** [microsoft/Dynamics365Commerce.InStore#41]
Hello,

I am trying to update my extensions to support release/9.42. I was able to update my code so that it builds just fine, but when I attempt to run it my custom HWS devices are not loading and the POS is throwing errors.

My initial test is focused on Store Commerce with a local/dedicated HWS.

![POS-HWS-Local](https://user-images.githubusercontent.com/5796906/227037213-da9ff7fc-60a2-4c72-a758-a6dbbaf0b3cd.png)

---

Error 1) When the POS interacts with my payment device I receive the following error in the event viewer.

```
Hardware Station operation failed for request uri: 'http://localhost/PaymentTerminal/Lock' with controller '' and method ''.
 isExternalPeripheralFailure: 'True'.
 ExceptionMessage: 'System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Commerce.Runtime.RequestHandlerAdapter' to type 'Microsoft.Dynamics.Commerce.Runtime.Handlers.INamedRequestHandler'.
   at Microsoft.Dynamics.Commerce.HardwareStation.PeripheralLockManager.Resolve[TPeripheral](AcquireLockRequest lockRequest, Type requestType, ResolveSource& source)
   at Microsoft.Dynamics.Commerce.HardwareStation.PeripheralLockManager.AcquireLock[TRequest,TPeripheral](AcquireLockRequest request)
   at Microsoft.Dynamics.Commerce.HardwareStation.Peripherals.PaymentTerminal.PaymentDeviceWrapper.LockDevice(LockPaymentTerminalDeviceRequest request)
   at Microsoft.Dynamics.Commerce.HardwareStation.Peripherals.PaymentTerminal.PaymentDeviceWrapper.Execute(Request request)
   at Microsoft.Dynamics.Commerce.Runtime.CommerceRuntime.<ExecuteCore>d__53`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dynamics.Commerce.Runtime.CommerceRuntime.<ExecuteCore>d__53`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.Commerce.Runtime.CommerceRuntime.<Execute>d__52`1.MoveNext()
...
```

The [documentation](https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/end-to-end-payment-extension#implement-the-inamedrequesthandler-interface) still does not reference INamedRequestHandlerAsync and the example [code](https://github.com/microsoft/Dynamics365Commerce.InStore/blob/release/9.42/src/HardwareStationSample/PaymentDevice/PaymentDeviceSample.cs) disables the compiler error with pragmas.

**_Should I be disabling the error as well and build to target the non-async INamedRequestHandler?_** In release/9.41 I did not update INamedRequestHandler to INamedRequestHandlerAsync, ignoring the warning, because I encountered the same issues that I am encountering now. My customizations worked correctly for release/9.41.

---

Error 2) When the POS interacts with my custom device I receive the following error in the event viewer. Possibly this is merely related to error 1.

```
Hardware Station operation failed for request uri: 'http://localhost/MyCustomDevice/MyCustomMethod' with controller '' and method ''.
 isExternalPeripheralFailure: 'False'.
 ExceptionMessage: 'System.InvalidOperationException: Composition does not have any instances of IHardwareStationController corresponding to the controller 'MyCustomDevice'
   at Microsoft.Dynamics.Commerce.HardwareStation.HardwareStationControllerSelector.GetControllerComponent(String controllerName, String methodName)
   at Microsoft.Dynamics.Commerce.HardwareStation.HardwareStationControllerSelector.SelectController(HttpRequestMessage request)
   at System.Web.Http.Tracing.Tracers.HttpControllerSelectorTracer.<>c__DisplayClass6_0.<System.Web.Http.Dispatcher.IHttpControllerSelector.SelectController>b__1()
   at System.Web.Http.Tracing.ITraceWriterExtensions.TraceBeginEnd(ITraceWriter traceWriter, HttpRequestMessage request, String category, TraceLevel level, String operatorName, String operationName, Action`1 beginTrace, Action execute, Action`1 endTrace, Action`1 errorTrace)
   at System.Web.Http.Tracing.Tracers.HttpControllerSelectorTracer.System.Web.Http.Dispatcher.IHttpControllerSelector.SelectController(HttpRequestMessage request)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__17`1.MoveNext()
...
```

The [documentation](https://learn.microsoft.com/en-us/dynamics365/commerce/dev-itpro/hardware-device-extension#sample-code-for-retail-sdk-version-10011-or-later) references IController, not IHardwareStationController. But it also is mentioning the Retail SDK, not the Commerce SDK, so it is obviously dated. Regardless, the example [code](https://github.com/microsoft/Dynamics365Commerce.InStore/blob/release/9.43/src/PackagingSamples/StoreCommerceApp/HardwareStation/FilePrinterController.cs) also references IController, so maybe "IHardwareStationController" is a rabbit trail and fixing error 1 will address this issue as well.

**Comment by rphillipsnwt** [comment]
Error 2 can be ignored, it is unrelated to error 1.

**Comment by thdigia** [comment]
@rphillipsnwt Did you find a solution to this? We bumped into this while upgrading our payment connectors from 9.39 to 9.42.

**Comment by rphillipsnwt** [comment]
@thdigia Use the "#pragma" directives like on lines 56 and 58 in the [sample](https://github.com/microsoft/Dynamics365Commerce.InStore/blob/release/9.42/src/HardwareStationSample/PaymentDevice/PaymentDeviceSample.cs) and keep it a INamedRequestHandler (non-async).

I don't know why they were so hasty to switch the async warning in .41 to an error in .42, but the approach for now seems to be ignoring the error.
